// src/components/RecipeList.js
import SpeghettiBolognese from './images/spaghetti-bolognese.jpg';
import ThaiGreenCurry from './images/thai-green-curry.jpg';
import ClassicFrenchOnionSoup from './images/french-onion-soup.jpg';
import HomemadeMargheritaPizza from './images/margherita-pizza.jpg';
import BeefandBroccoliStirFry from './images/beef-broccoli.jpg';
import { v4 as uuidv4 } from 'uuid';

// src/data/recipeData.js

const recipes = [
  {
    id: uuidv4(),
    title: 'Spaghetti Bolognese',
    image: SpeghettiBolognese,
    prepTime: '15 mins',
    cookTime: '45 mins',
    servings: 4,
    difficulty: 'Easy',
    cuisine: 'Italian',
    ingredients: [
      '400g spaghetti',
      '500g ground beef',
      '2 cans crushed tomatoes',
      '1 large onion, finely chopped',
      '3 cloves garlic, minced',
      '2 carrots, diced',
      '2 celery stalks, diced',
      '2 tbsp olive oil',
      '1 tbsp dried oregano',
      '1 tbsp dried basil',
      'Salt and pepper to taste',
      'Grated Parmesan cheese for serving'
    ],
    instructions: [
      'Heat olive oil in a large pot over medium heat',
      'Add onion, carrots, and celery. Cook until softened, about 5 minutes',
      'Add garlic and cook for another minute',
      'Add ground beef and cook until browned, breaking up any lumps',
      'Stir in crushed tomatoes, oregano, and basil',
      'Simmer for 30 minutes, stirring occasionally',
      'Meanwhile, cook spaghetti according to package instructions',
      'Season sauce with salt and pepper to taste',
      'Serve sauce over spaghetti with grated Parmesan'
    ],
    tags: [
      'pasta',
      'spaghetti',
      'meat',
      'beef',
      'pork',
      'tomato',
      'sauce',
      'bolognese',
      'ragu',
      'dinner',
      'lunch',
      'family meal',
      'comfort food',
      'italian',
      'italian cuisine',
      'easy recipe',
      'weeknight dinner',
      'weekend meal',
      'kid-friendly',
      'gluten-free',
      'dairy-free',
      'vegetarian',
      'vegan',
      'spicy',
      'mild',
      'flavorful',
      'hearty',
      'savory',
      'homemade',
      'fresh ingredients',
      'slow cooker',
      'instant pot',
      'stovetop',
      'oven-baked',
      'party food',
      'potluck',
      'leftovers',
      'freezer-friendly',
      'budget-friendly',
      'gourmet',
      'classic',
      'traditional',
      'modern',
      'fusion',
      'healthy',
      'nutritious',
      'low-carb',
      'high-protein',
      'keto',
      'paleo',
      'whole30',
      'pescatarian',
      'plant-based',
      'gluten-free pasta',
      'zucchini noodles',
      'shirataki noodles',
      'cauliflower rice',
      'vegan cheese',
      'dairy-free cheese'
    ]
  },
  {
    id: uuidv4(),
    title: 'Thai Green Curry',
    image: ThaiGreenCurry,
    prepTime: '20 mins',
    cookTime: '30 mins',
    servings: 4,
    difficulty: 'Medium',
    cuisine: 'Thai',
    ingredients: [
      '400g chicken breast, sliced',
      '2 cans coconut milk',
      '3 tbsp green curry paste',
      '2 bell peppers, sliced',
      '1 cup bamboo shoots',
      '1 cup snap peas',
      'Fish sauce to taste',
      'Palm sugar to taste',
      'Thai basil leaves',
      'Jasmine rice for serving'
    ],
    instructions: [
      'Heat coconut milk in a large pan until it starts to bubble',
      'Add green curry paste and stir until fragrant',
      'Add chicken and cook until no longer pink',
      'Add vegetables and simmer until tender',
      'Season with fish sauce and palm sugar',
      'Garnish with Thai basil leaves',
      'Serve hot with jasmine rice'
    ],
    tags: [
      'thai',
      'thai cuisine',
      'curry',
      'green curry',
      'spicy',
      'flavorful',
      'coconut milk',
      'vegetable',
      'protein',
      'chicken',
      'beef',
      'pork',
      'shrimp',
      'tofu',
      'vegetable curry',
      'dinner',
      'lunch',
      'weeknight meal',
      'weekend meal',
      'easy recipe',
      'quick recipe',
      'healthy',
      'nutritious',
      'gluten-free',
      'dairy-free',
      'vegan',
      'vegetarian',
      'hot',
      'medium',
      'mild',
      'aromatic',
      'fresh herbs',
      'ginger',
      'garlic',
      'chili pepper',
      'kaffir lime leaves',
      'lemongrass',
      'fish sauce',
      'soy sauce',
      'rice',
      'noodles',
      'stir-fry',
      'soup',
      'stew',
      'comfort food',
      'exotic',
      'authentic',
      'fusion',
      'budget-friendly',
      'gourmet',
      'party food',
      'potluck',
      'leftovers',
      'freezer-friendly'
  ]
  },
  {
    id: uuidv4(),
    title: 'Classic French Onion Soup',
    image: ClassicFrenchOnionSoup,
    prepTime: '15 mins',
    cookTime: '1 hour 15 mins',
    servings: 6,
    difficulty: 'Medium',
    cuisine: 'French',
    ingredients: [
      '6 large onions, thinly sliced',
      '4 tbsp butter',
      '2 tbsp olive oil',
      '1 tsp sugar',
      '2 cloves garlic, minced',
      '8 cups beef broth',
      '1/2 cup dry white wine',
      '1 bay leaf',
      '4 sprigs fresh thyme',
      'Baguette slices',
      'Gruyere cheese, grated',
      'Salt and pepper to taste'
    ],
    instructions: [
      'In a large pot, melt butter with olive oil over medium heat',
      'Add sliced onions and sugar, cook until deeply caramelized (45 mins)',
      'Add garlic and cook for 1 minute',
      'Pour in wine and scrape up any browned bits',
      'Add beef broth, bay leaf, and thyme',
      'Simmer for 30 minutes',
      'Toast baguette slices',
      'Ladle soup into oven-safe bowls',
      'Top with toasted bread and cheese',
      'Broil until cheese is bubbly and golden'
    ],
    tags: [
      'french',
      'french cuisine',
      'soup',
      'onion soup',
      'french onion soup',
      'comfort food',
      'winter food',
      'cozy',
      'warm',
      'hearty',
      'savory',
      'caramelized onion',
      'cheese',
      'gruyère',
      'baguette',
      'crouton',
      'broth',
      'beef broth',
      'chicken broth',
      'vegetable broth',
      'garlic',
      'thyme',
      'bay leaf',
      'black pepper',
      'easy recipe',
      'weeknight dinner',
      'weekend meal',
      'gluten-free',
      'dairy-free',
      'vegetarian',
      'vegan',
      'low-carb',
      'keto',
      'paleo',
      'whole30',
      'party food',
      'potluck',
      'leftovers',
      'freezer-friendly',
      'classic',
      'traditional',
      'elegant',
      'gourmet'
  ]
  },
  {
    id: uuidv4(),
    title: 'Homemade Margherita Pizza',
    image: HomemadeMargheritaPizza,
    prepTime: '30 mins',
    cookTime: '15 mins',
    servings: 2,
    difficulty: 'Medium',
    cuisine: 'Italian',
    ingredients: [
      '300g pizza dough',
      '200g San Marzano tomatoes',
      '200g fresh mozzarella',
      'Fresh basil leaves',
      'Extra virgin olive oil',
      'Salt to taste'
    ],
    instructions: [
      'Preheat oven to highest setting with pizza stone inside',
      'Stretch dough into a 12-inch circle',
      'Spread crushed tomatoes leaving a border',
      'Tear mozzarella and distribute evenly',
      'Slide pizza onto hot stone',
      'Bake until crust is charred and cheese is bubbling',
      'Top with fresh basil and drizzle with olive oil'
    ],
    tags: [
      'pizza',
      'margherita pizza',
      'italian',
      'italian cuisine',
      'homemade',
      'pizza dough',
      'tomato sauce',
      'mozzarella cheese',
      'basil',
      'olive oil',
      'garlic',
      'oregano',
      'dinner',
      'lunch',
      'weeknight meal',
      'weekend meal',
      'family meal',
      'party food',
      'easy recipe',
      'kid-friendly',
      'gluten-free',
      'dairy-free',
      'vegan',
      'vegetarian',
      'healthy',
      'nutritious',
      'low-carb',
      'keto',
      'paleo',
      'whole30',
      'fresh ingredients',
      'oven-baked',
      'crispy crust',
      'cheesy',
      'flavorful',
      'authentic',
      'classic',
      'traditional',
      'modern',
      'fusion',
      'budget-friendly',
      'gourmet'
  ]
  },
  {
    id: uuidv4(),
    title: 'Beef and Broccoli Stir-Fry',
    image: BeefandBroccoliStirFry,
    prepTime: '20 mins',
    cookTime: '15 mins',
    servings: 4,
    difficulty: 'Easy',
    cuisine: 'Chinese',
    ingredients: [
      '500g flank steak, sliced',
      '2 cups broccoli florets',
      '3 tbsp soy sauce',
      '2 tbsp oyster sauce',
      '1 tbsp cornstarch',
      '2 cloves garlic, minced',
      '1 tbsp ginger, minced',
      'Sesame oil',
      'White rice for serving'
    ],
    instructions: [
      'Marinate beef in soy sauce, cornstarch for 15 minutes',
      'Blanch broccoli in boiling water for 2 minutes',
      'Heat wok over high heat',
      'Stir-fry beef until browned',
      'Add garlic and ginger',
      'Add broccoli and sauces',
      'Stir-fry until heated through',
      'Drizzle with sesame oil',
      'Serve over rice'
    ],
    tags: [
      'stir-fry',
      'chinese',
      'chinese cuisine',
      'beef',
      'broccoli',
      'vegetable',
      'soy sauce',
      'oyster sauce',
      'cornstarch',
      'garlic',
      'ginger',
      'sesame oil',
      'dinner',
      'lunch',
      'weeknight meal',
      'quick recipe',
      'easy recipe',
      'healthy',
      'nutritious',
      'gluten-free',
      'dairy-free',
      'low-carb',
      'keto',
      'paleo',
      'whole30',
      'fresh ingredients',
      'wok',
      'skillet',
      'flavorful',
      'savory',
      'umami',
      'authentic',
      'fusion',
      'budget-friendly',
      'gourmet',
      'leftovers',
      'freezer-friendly'
  ]
  }
];

export default recipes;